# Generated by Django 2.2.6 on 2022-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzeriaManager', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pizza_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
