# Generated by Django 2.2.6 on 2022-03-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PizzeriaManager", "0003_orderitem_pizza_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
