# Generated by Django 3.1.12 on 2022-06-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PizzeriaManager", "0012_auto_20220601_2251"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
